export const GITHUB_OAUTH_CLIENT_ID = process.env.NEXT_PUBLIC_GITHUB_OAUTH_CLIENT_ID ?? '';

export const GITHUB_OAUTH_REDIRECT_URI = process.env
  .NEXT_PUBLIC_GITHUB_OAUTH_REDIRECT_URI ?? '';

export const MAEIL_WIKI_ERROR_PAGE_URL = process.env
  .NEXT_PUBLIC_MAEIL_WIKI_ERROR_PAGE_URL ?? '';
